name: Build Project
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
  push:
    branches: [main]
    paths-ignore:
      - "**.md"

jobs:
  test-versioning:
    name: 📦 Test, Versioning ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.9.0]
      max-parallel: 1

    steps:
      - name: Generate token for GitHub App
        id: generate-token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_CLIENT_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}

      - name: Python Semantic Release
        id: release
        if: github.ref_name == 'main' && github.event_name == 'push'
        uses: python-semantic-release/python-semantic-release@v8.7.0
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
